[config]
default_type = "dark"

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout.css'
output_path = '~/.config/wlogout/colors.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'