# wallust.toml
backend = "fastaneal"
color_space = "lab"
threshold = 20

[[templates]]
src = 'colors.conf'
dst = '~/.config/hypr/colors.conf'

[[templates]]
src = 'waybar.css'
dst = '~/.config/waybar/colors.css'

[[templates]]
src = 'wlogout.css'
dst = '~/.config/wlogout/colors.css'

[[templates]]
src = 'kitty.conf'
dst = '~/.config/kitty/colors.conf'